library(shiny)
library(dplyr)
library(purrr)
library(ggplot2)
library(readr)
library(stringr)
library(tibble)
library(DT)


# Detailed explorer datasets are maintained in the category-specific dashboards.
# The collection overview uses only the overview, data-quality, and variable-completeness files below.

# Study-level overview file used by the Study Overview tab.
overview_path <- "data/rolls_collection_overview(Overview).csv"

if (!file.exists(overview_path)) {
  stop(
    paste0(
      "The Rolls Collection overview CSV was not found.\n\n",
      "Place it here:\n",
      "app/data/rolls_collection_overview(Overview).csv"
    )
  )
}

overview <- read_csv(
  overview_path,
  locale = locale(encoding = "Windows-1252"),
  show_col_types = FALSE,
  na = c("", "NA")
)

overview_original_columns <- names(overview)

# ============================================================
# DATA QUALITY
# ============================================================
# Generated by the rolls-metadata pipeline.
#
# Study-level groups:
#   All data
#   Measured intake
#   Macronutrient intake
#   Total intake
#   Questionnaire data

data_quality_path <- "data/dashboard_data_quality.csv"
dataset_data_quality_path <- "data/dashboard_dataset_data_quality.csv"

if (!file.exists(data_quality_path)) {
  stop(
    paste0(
      "The study-level dashboard data quality CSV was not found.\n\n",
      "Run the rolls-metadata pipeline through Script 08, then copy:\n",
      "outputs/dashboard_data_quality.csv\n\n",
      "to:\n",
      "app/data/dashboard_data_quality.csv"
    )
  )
}

if (!file.exists(dataset_data_quality_path)) {
  stop(
    paste0(
      "The dataset-level dashboard data quality CSV was not found.\n\n",
      "Run the rolls-metadata pipeline through Script 08, then copy:\n",
      "outputs/dashboard_dataset_data_quality.csv\n\n",
      "to:\n",
      "app/data/dashboard_dataset_data_quality.csv"
    )
  )
}

data_quality <- read_csv(
  data_quality_path,
  show_col_types = FALSE,
  na = c("", "NA")
)

dataset_data_quality <- read_csv(
  dataset_data_quality_path,
  show_col_types = FALSE,
  na = c("", "NA")
)

variable_completeness_path <- "data/dashboard_variable_completeness.csv"

if (!file.exists(variable_completeness_path)) {
  stop(
    paste0(
      "The variable-level completeness CSV was not found.\n\n",
      "Copy outputs/dashboard_variable_completeness.csv from the rolls-metadata project to:\n",
      "app/data/dashboard_variable_completeness.csv"
    )
  )
}

variable_completeness <- read_csv(
  variable_completeness_path,
  show_col_types = FALSE,
  na = c("", "NA")
)

variable_completeness_required <- c(
  "study",
  "Dataset",
  "Variable",
  "Type",
  "Total observations",
  "Complete observations",
  "Missing observations",
  "% complete",
  "% missing"
)

variable_completeness_missing <- setdiff(
  variable_completeness_required,
  names(variable_completeness)
)

if (length(variable_completeness_missing) > 0) {
  stop(
    paste(
      "The variable-level completeness CSV is missing these required columns:",
      paste(variable_completeness_missing, collapse = ", ")
    )
  )
}

variable_completeness <- variable_completeness %>%
  mutate(
    study = as.character(study),
    study_display = str_to_title(str_replace_all(study, "_", " "))
  )

dataset_explorer_study_choices <- sort(unique(variable_completeness$study_display))
dataset_explorer_variable_choices <- sort(unique(variable_completeness$Variable))

data_quality_required <- c(
  "study",
  "# variables observed",
  "Total data points",
  "Total missing",
  "% missing overall",
  "% data present",
  "Mean % missing by participant",
  "Range of % missing by participant",
  "# complete cases",
  "# participants ≥85% complete",
  "Intake macros computed"
)

dataset_data_quality_required <- c(
  "study",
  "Dataset",
  "# variables observed",
  "Total data points",
  "Total missing",
  "% missing overall",
  "% data present",
  "Mean % missing by participant",
  "Range of % missing by participant",
  "# complete cases",
  "# participants ≥85% complete"
)

data_quality_missing <- setdiff(data_quality_required, names(data_quality))
dataset_data_quality_missing <- setdiff(
  dataset_data_quality_required,
  names(dataset_data_quality)
)

if (length(data_quality_missing) > 0) {
  stop(
    paste(
      "The study-level dashboard data quality CSV is missing these required columns:",
      paste(data_quality_missing, collapse = ", ")
    )
  )
}

if (length(dataset_data_quality_missing) > 0) {
  stop(
    paste(
      "The dataset-level dashboard data quality CSV is missing these required columns:",
      paste(dataset_data_quality_missing, collapse = ", ")
    )
  )
}

data_quality <- data_quality %>%
  mutate(
    study = as.character(study),
    study_display = str_to_title(str_replace_all(study, "_", " ")),
    `Data group` = factor(
      `Data group`,
      levels = c(
        "All data",
        "Demographic data",
        "Measured intake",
        "Macronutrient intake",
        "Questionnaire data"
      )
    )
  )

# Remove only records that are actually the mealtime dataset/study.
# Keep the regular 1992 EatDis deprivation study.
data_quality <- data_quality %>%
  filter(
    !str_detect(
      study,
      regex("mealtime", ignore_case = TRUE)
    ),
    !str_detect(
      study_display,
      regex("mealtime", ignore_case = TRUE)
    )
  )

dataset_data_quality <- dataset_data_quality %>%
  mutate(
    study = as.character(study),
    study_display = str_to_title(str_replace_all(study, "_", " "))
  ) %>%
  filter(
    !str_detect(
      study,
      regex("mealtime", ignore_case = TRUE)
    ),
    !str_detect(
      study_display,
      regex("mealtime", ignore_case = TRUE)
    ),
    !str_detect(
      Dataset,
      regex("mealtime", ignore_case = TRUE)
    )
  )

# Build the dropdown after removing only the mealtime entry.
data_quality_study_choices <- sort(
  unique(data_quality$study_display)
)

overview_required <- c(
  "study", "year", "location", "sample_age", "sample_sex",
  "dataset", "study_n", "sub_n", "pub_doi"
)

overview_missing <- setdiff(overview_required, names(overview))

if (length(overview_missing) > 0) {
  stop(
    paste(
      "The overview file is missing these required columns:",
      paste(overview_missing, collapse = ", ")
    )
  )
}

# Variables marked 1 are treated as present. Blank cells, 0, 2, and text such
# as "missing" do not count as a positive occurrence in the filters.
positive_flag <- function(x) {
  numeric_x <- suppressWarnings(as.numeric(as.character(x)))
  !is.na(numeric_x) & numeric_x == 1
}

format_doi_links <- function(x, study_name) {
  if (is.na(x) || !nzchar(str_trim(as.character(x)))) {
    return("")
  }
  
  doi_values <- str_split(as.character(x), "\\s*;\\s*", simplify = FALSE)[[1]]
  doi_values <- str_trim(doi_values)
  doi_values <- doi_values[nzchar(doi_values)]
  
  study_word <- str_split(
    str_trim(str_to_title(str_replace_all(as.character(study_name), "_", " "))),
    "\\s+",
    simplify = FALSE
  )[[1]][1]
  
  links <- vapply(
    seq_along(doi_values),
    function(i) {
      doi_value <- doi_values[i]
      link_url <- doi_value
      
      if (!str_detect(link_url, regex("^https?://", ignore_case = TRUE))) {
        link_url <- paste0(
          "https://doi.org/",
          str_remove(link_url, regex("^doi:\\s*", ignore_case = TRUE))
        )
      }
      
      link_text <- if (length(doi_values) > 1) {
        paste("Paper", i, "DOI")
      } else {
        "Paper DOI"
      }
      
      paste0(
        '<a href="',
        htmltools::htmlEscape(link_url, attribute = TRUE),
        '" target="_blank" rel="noopener noreferrer">',
        htmltools::htmlEscape(link_text),
        '</a>'
      )
    },
    character(1)
  )
  
  paste(links, collapse = "<br>")
}

study_method_choices <- c(
  "Sensory-specific satiety" = "sss",
  "Preload before measured intake" = "preload_used",
  "Energy-density manipulation" = "ed_manipulation",
  "Portion-size manipulation" = "ps_manipulation",
  "Volume manipulation" = "volume_manipulation",
  "Fat-content manipulation" = "fat_manipulation",
  "Food-form manipulation" = "food_form",
  "Microstructure / coded videos" = "microstructure",
  "Eating-disorder sample" = "eating_disorder",
  "Weight-loss sample or intervention" = "weight_loss",
  "Obesity sample" = "obesity",
  "Social-context manipulation" = "social_context"
)

study_method_choices <- study_method_choices[
  study_method_choices %in% names(overview)
]

demographic_choices <- c(
  "Age" = "age",
  "Sex" = "sex",
  "Race" = "race",
  "Socioeconomic status" = "ses",
  "BMI" = "bmi"
)

demographic_choices <- demographic_choices[
  demographic_choices %in% names(overview)
]

intake_measure_choices <- c(
  "Recall intake" = "recall_intake",
  "Measured intake" = "measured_intake",
  "Pre/post-meal questions" = "pre_post_meal_q",
  "Food preference" = "food_preference",
  "Eating duration" = "eat_duration",
  "Substance use" = "substance_use",
  "Current-status questions" = "current_status_q"
)

intake_measure_choices <- intake_measure_choices[
  intake_measure_choices %in% names(overview)
]

nutrient_columns <- intersect(
  c("cho_intake", "fat_intake", "pro_intake", "fiber_intake"),
  names(overview)
)

questionnaire_choices <- c(
  "Zung" = "zung",
  "EAT" = "eat",
  "EDI" = "edi",
  "EI" = "ei",
  "Beck" = "beck",
  "BSQ" = "bsq",
  "QEWP-R" = "qewp-r",
  "DEBQ" = "debq",
  "PFS" = "pfs",
  "CFQ" = "cfq",
  "UPSIT" = "upsit"
)

questionnaire_choices <- questionnaire_choices[
  questionnaire_choices %in% names(overview)
]

overview <- overview %>%
  filter(!is.na(study) & nzchar(str_trim(as.character(study)))) %>%
  mutate(
    study = as.character(study),
    dataset = as.character(dataset),
    study_display = str_to_title(str_replace_all(study, "_", " ")),
    dataset_display = if_else(
      is.na(dataset) | !nzchar(str_trim(dataset)),
      "",
      str_to_title(str_replace_all(dataset, "_", " "))
    )
  ) %>%
  add_count(study, name = "rows_in_study") %>%
  mutate(
    sample_size = if_else(
      rows_in_study > 1 & !is.na(suppressWarnings(as.numeric(sub_n))),
      suppressWarnings(as.numeric(sub_n)),
      suppressWarnings(as.numeric(study_n))
    )
  )

location_choices <- sort(unique(na.omit(as.character(overview$location))))
year_choices <- sort(unique(na.omit(overview$year)))
age_group_choices <- sort(unique(na.omit(as.character(overview$sample_age))))
sex_composition_choices <- sort(unique(na.omit(as.character(overview$sample_sex))))

app_css <- "
body {
  background: #ffffff;
}

.navbar {
  background-color: #eaf4fb !important;
  border-bottom: 1px solid #b8d6ea !important;
  min-height: 64px;
}

.navbar .navbar-brand {
  color: #005b8f !important;
  font-size: 22px !important;
  font-weight: 700 !important;
  padding-top: 18px !important;
  padding-bottom: 18px !important;
}

.navbar .nav-link {
  background-color: #ffffff !important;
  color: #005b8f !important;
  font-size: 17px !important;
  font-weight: 700 !important;
  margin: 8px 4px !important;
  padding: 12px 16px !important;
  border: 1px solid #b8d6ea !important;
  border-radius: 8px !important;
}

.navbar .nav-link:hover,
.navbar .nav-link:focus,
.navbar .nav-item.active .nav-link,
.navbar .nav-link.active {
  background-color: #ffffff !important;
  color: #005b8f !important;
  border-color: #005b8f !important;
  box-shadow: none !important;
}

.well,
.card-like {
  background: #ffffff;
  border: 1px solid #d6e4ef;
  border-radius: 14px;
  padding: 18px;
}

a:focus,
button:focus,
input:focus,
select:focus {
  outline: 3px solid #0072B2 !important;
  outline-offset: 2px;
}

.section-title {
  color: #005b8f;
  font-weight: 700;
  margin-bottom: 16px;
}

.tab-page-title {
  color: #005b8f;
  font-size: 28px;
  font-weight: 700;
  line-height: 1.2;
  margin-top: 10px;
  margin-bottom: 18px;
}

.home-hero {
  max-width: 1050px;
  margin: 35px auto 0 auto;
}

.home-photo {
  width: 100%;
  max-width: 310px;
  height: auto;
  border-radius: 12px;
  border: 1px solid #d6e4ef;
  display: block;
  margin: 0 auto 24px auto;
}

.home-copy {
  font-size: 17px;
  line-height: 1.65;
}

.home-link {
  display: inline-block;
  margin-top: 10px;
  font-weight: 700;
}

.home-contact {
  margin-top: 35px;
  padding-top: 20px;
  border-top: 1px solid #d6e4ef;
  font-size: 15px;
  line-height: 1.6;
}
"

ui <- navbarPage(
  title = "Rolls Collection",
  id = "main_navigation",
  header = tags$head(
    tags$style(HTML(app_css)),
    tags$script(
      HTML("
        $(document).on('click', '.study-quality-link', function(e) {
          e.preventDefault();
          var study = $(this).attr('data-study');
          Shiny.setInputValue(
            'study_quality_click',
            {
              study: study,
              nonce: Date.now() + Math.random()
            },
            {priority: 'event'}
          );
        });
      ")
    )
  ),
  
  tabPanel(
    "Home",
    fluidPage(
      div(
        class = "home-hero",
        fluidRow(
          column(
            width = 4,
            tags$img(
              src = "Barbara.jpg",
              alt = "Barbara J. Rolls",
              class = "home-photo"
            )
          ),
          column(
            width = 8,
            h1(class = "section-title", "Rolls Collection"),
            div(
              class = "home-copy",
              p(
                "The Rolls Collection brings together curated data and documentation ",
                "from studies led by Barbara J. Rolls and the Laboratory for the Study ",
                "of Human Ingestive Behavior. The collection includes information on ",
                "study design, participants, questionnaires, eating behavior, and food intake."
              ),
              h3("Explore the Rolls Collection"),
              tags$ul(
                tags$li(tags$strong("Collection Overview: "), "Use this dashboard to browse studies across the full Rolls Collection, review data quality, and identify available datasets and variables."),
                tags$li(
                  tags$strong("View studies in detail: "),
                  tags$a(
                    href = "https://penn-state-rolls-collection.github.io/adult-portion-size/",
                    "Adult Portion Size"
                  ),
                  ", Energy Density, Variety, Sensory-Specific Satiety, and Child Studies. Additional detailed category dashboards will be linked here as they become available."
                )
              ),
              tags$a(
                href = "https://scholarsphere.psu.edu/resources/52cfbdb6-d420-4a5c-a85a-4e5aa099e519",
                target = "_blank",
                rel = "noopener noreferrer",
                class = "home-link",
                "View the Rolls Collection in ScholarSphere"
              )
            )
          )
        ),
        div(
          class = "home-contact",
          p(
            tags$strong("Questions about the collection: "),
            tags$a(
              href = "mailto:researchdatastewardshipprogram@PennStateOffice365.onmicrosoft.com",
              "researchdatastewardshipprogram@PennStateOffice365.onmicrosoft.com"
            )
          ),
          p(
            tags$strong("Dashboard curated and maintained by Alaina Pearce: "),
            tags$a(
              href = "mailto:azp271@psu.edu",
              "azp271@psu.edu"
            )
          ),
          p(
            tags$strong("Barbara J. Rolls, Ph.D.: "),
            tags$a(
              href = "mailto:bjr4@psu.edu",
              "bjr4@psu.edu"
            )
          )
        )
      )
    )
  ),
  
  tabPanel(
    "README",
    fluidPage(
      h2(class = "tab-page-title", "README"),
      p(
        "This page provides a guide to the Rolls Collection dashboard, including how to navigate the dashboard, ",
        "how to use the Study Overview filters, and what information is available on each tab."
      ),
      
      tags$hr(),
      
      h3("How to use the dashboard"),
      p(
        "A useful place to start is the Study Overview tab. Use its filters to identify studies with the characteristics, ",
        "measures, or questionnaires you are interested in. Click a study name to open the Data Quality tab with that study selected. ",
        "Use Dataset Explorer to identify datasets and variables available across the collection."
      ),
      
      h3("Study Overview"),
      p(
        "The Study Overview tab can be searched by study name, dataset, location, year, or DOI. ",
        "The filters can also be used to narrow studies by study methods and sample characteristics, macronutrients, ",
        "demographic variables, and questionnaires or related measures."
      ),
      
      h4("Study methods and sample characteristics"),
      tags$ul(
        tags$li(tags$strong("Sensory-specific satiety: "), "identifies studies involving sensory-specific satiety."),
        tags$li(tags$strong("Preload before measured intake: "), "identifies studies that used a preload before measured intake."),
        tags$li(tags$strong("Energy-density manipulation: "), "identifies studies that manipulated energy density."),
        tags$li(tags$strong("Portion-size manipulation: "), "identifies studies that manipulated portion size."),
        tags$li(tags$strong("Volume manipulation: "), "identifies studies that manipulated volume."),
        tags$li(tags$strong("Fat-content manipulation: "), "identifies studies that manipulated fat content."),
        tags$li(tags$strong("Food-form manipulation: "), "identifies studies that manipulated food form."),
        tags$li(tags$strong("Microstructure / coded videos: "), "identifies studies with microstructure or coded-video measures."),
        tags$li(tags$strong("Eating-disorder sample: "), "identifies studies that included an eating-disorder sample."),
        tags$li(tags$strong("Weight-loss sample or intervention: "), "identifies studies with a weight-loss sample or intervention."),
        tags$li(tags$strong("Obesity sample: "), "identifies studies that included an obesity sample."),
        tags$li(tags$strong("Social-context manipulation: "), "identifies studies that manipulated social context.")
      ),
      
      h4("Demographic variables"),
      p(
        "The demographic filters identify studies containing the selected participant characteristics. ",
        "The dashboard currently checks for age, sex, race, socioeconomic status, and BMI when those fields are available."
      ),
      
      h4("Macronutrients"),
      p(
        "The macronutrient filter identifies whether a study contains macronutrient information. ",
        "The Study Overview data currently checks carbohydrate, fat, protein, and fiber intake fields when available."
      ),
      
      h4("Questionnaires and related measures"),
      p(
        "The questionnaire filters identify studies containing the selected questionnaire ",
        "or related measure. These measures assess areas such as eating behavior, mood, ",
        "body image, food-related thoughts, and sensory function."
      ),
      tags$ul(
        tags$li(
          tags$strong("Zung: "),
          "a self-report measure used to assess symptoms related to depression."
        ),
        tags$li(
          tags$strong("EAT (Eating Attitudes Test): "),
          "a questionnaire used to assess attitudes and behaviors associated with disordered eating."
        ),
        tags$li(
          tags$strong("EDI (Eating Disorder Inventory): "),
          "a questionnaire assessing behavioral and psychological characteristics associated with eating disorders."
        ),
        tags$li(
          tags$strong("EI: "),
          "an eating-related questionnaire included in selected studies in the collection."
        ),
        tags$li(
          tags$strong("Beck: "),
          "a self-report measure used to assess symptoms related to depression."
        ),
        tags$li(
          tags$strong("BSQ (Body Shape Questionnaire): "),
          "a questionnaire assessing concerns and feelings related to body shape."
        ),
        tags$li(
          tags$strong("QEWP-R (Questionnaire on Eating and Weight Patterns-Revised): "),
          "a questionnaire used to assess patterns and behaviors related to eating and weight."
        ),
        tags$li(
          tags$strong("DEBQ (Dutch Eating Behavior Questionnaire): "),
          "a questionnaire assessing eating behaviors such as restrained, emotional, and external eating."
        ),
        tags$li(
          tags$strong("PFS (Power of Food Scale): "),
          "a measure of thoughts, feelings, and responses related to the availability and appeal of food."
        ),
        tags$li(
          tags$strong("CFQ: "),
          "a food-related questionnaire included in selected studies in the collection."
        ),
        tags$li(
          tags$strong("UPSIT (University of Pennsylvania Smell Identification Test): "),
          "a standardized measure of odor identification ability."
        )
      ),
      
      tags$hr(),
      
      h3("Data Quality"),
      p(
        "The Data Quality tab summarizes missingness and completeness for a selected study. ",
        "The study-level table summarizes the study overall and by data group, while the dataset-level table provides ",
        "a separate summary for each individual CSV dataset contributing to the study."
      ),
      tags$ul(
        tags$li(tags$strong("All data: "), "all observed variables included in the study."),
        tags$li(tags$strong("Demographic data: "), "participant characteristics such as age, sex, race, BMI, and related demographic measures when available."),
        tags$li(tags$strong("Measured intake: "), "directly measured consumption, such as grams or kcal."),
        tags$li(tags$strong("Macronutrient intake: "), "protein, fat, carbohydrate, and related nutrient measures."),
        tags$li(tags$strong("Questionnaire data: "), "questionnaire, rating, preference, and related self-report measures.")
      ),
      p(
        "The tables report the number of observed variables, total data points, total missing values, overall missingness, ",
        "participant-level missingness, complete cases, and the number of participants who are at least 85% complete."
      ),
      
      tags$hr(),
      
      h3("Dataset Explorer"),
      p(
        "The Dataset Explorer can be used in two ways. Browse a dataset by selecting a study and dataset to view its variables ",
        "and completeness, or search for a variable to see every study and dataset in the collection where that variable appears."
      ),
      
      h3("Detailed study dashboards"),
      p("The Collection Overview dashboard is designed for browsing the full Rolls Collection. More detailed dashboards will focus on major study categories so users can explore category-specific data without loading the entire collection at once."),
      tags$ul(
        tags$li(
          tags$a(
            href = "https://penn-state-rolls-collection.github.io/adult-portion-size/",
            tags$strong("Adult Portion Size")
          ),
          ": detailed dashboard for adult portion-size studies."
        ),
        tags$li(tags$strong("Energy Density: "), "detailed dashboard for energy-density studies."),
        tags$li(tags$strong("Variety: "), "detailed dashboard for variety studies."),
        tags$li(tags$strong("Sensory-Specific Satiety: "), "detailed dashboard for sensory-specific satiety studies."),
        tags$li(tags$strong("Child Studies: "), "detailed dashboard for studies focused on children.")
      ),
      p("The Adult Portion Size dashboard is available now. Links to additional detailed dashboards will be added as they become available."),
      tags$hr(),
      h3("Recommended navigation"),
      tags$ol(
        tags$li("Use Study Overview to identify studies that match your interests."),
        tags$li("Click a study name to review its Data Quality information."),
        tags$li("Use Dataset Explorer to identify datasets and variables available across the collection."),
        tags$li("Use a detailed study-category dashboard when you want to explore category-specific data in more depth.")
      ),
      
      p(
        "Not every study contains every type of measure, questionnaire, demographic variable, or dataset. ",
        "The available options therefore differ across studies."
      )
    )
  ),
  
  tabPanel(
    "Study Overview",
    fluidPage(
      sidebarLayout(
        sidebarPanel(
          h4("Find studies"),
          textInput(
            inputId = "overview_search",
            label = "Search studies:",
            placeholder = "Study name, dataset, location, year, or DOI"
          ),
          checkboxGroupInput(
            inputId = "overview_methods",
            label = "Study methods and sample characteristics:",
            choices = study_method_choices
          ),
          radioButtons(
            inputId = "overview_nutrients",
            label = "Macronutrients assessed:",
            choices = c(
              "Show all" = "all",
              "Yes" = "yes",
              "No" = "no"
            ),
            selected = "all"
          ),
          checkboxGroupInput(
            inputId = "overview_demographics",
            label = "Demographic variables present:",
            choices = demographic_choices
          ),
          checkboxGroupInput(
            inputId = "overview_questionnaires",
            label = "Questionnaires and related measures:",
            choices = questionnaire_choices
          ),
          actionButton(
            inputId = "clear_overview_filters",
            label = "Clear filters",
            class = "btn-default"
          )
        ),
        mainPanel(
          h2(class = "tab-page-title", "Study Overview"),
          p(
            "Click a study name in the table below to open the Data Quality tab ",
            "with that study automatically selected."
          ),
          DTOutput("study_overview_table")
        )
      )
    )
  ),
  
  tabPanel(
    "Data Quality",
    value = "data_quality",
    fluidPage(
      h2(class = "tab-page-title", "Data Quality"),
      p(
        "Select a study to view study-level missingness and completeness metrics, ",
        "followed by a breakdown for the individual datasets that contribute to that study."
      ),
      wellPanel(
        selectInput(
          inputId = "quality_study",
          label = "Choose a study:",
          choices = data_quality_study_choices,
          selected = if (length(data_quality_study_choices) > 0) {
            data_quality_study_choices[1]
          } else {
            character(0)
          }
        )
      ),
      h4("Study-level summary"),
      p(
        "This table summarizes data availability and missingness across the selected study. ",
        "The All data row describes the study overall, while the remaining rows summarize specific types of variables available in the curated data."
      ),
      DTOutput("data_quality"),
      tags$div(
        class = "card-like",
        style = "margin-top: 18px;",
        tags$strong("Data groups"),
        tags$ul(
          tags$li(tags$strong("All data: "), "all observed variables included in the study."),
          tags$li(tags$strong("Demographic data: "), "participant characteristics such as age, sex, race, BMI, and related demographic measures when available."),
          tags$li(tags$strong("Measured intake: "), "directly measured consumption, such as grams or kcal."),
          tags$li(tags$strong("Macronutrient intake: "), "protein, fat, carbohydrate, and related nutrient measures."),
          tags$li(tags$strong("Questionnaire data: "), "questionnaire, rating, preference, and related self-report measures.")
        )
      ),
      uiOutput("macro_status"),
      tags$hr(),
      h4("Dataset-level detail"),
      p(
        "Each row represents one individual CSV dataset within the selected study. ",
        "The table summarizes the variables and observations available in that dataset, including overall missingness and participant-level completeness. ",
        "Variables that are 100% empty within a dataset are excluded from the missingness denominator."
      ),
      DTOutput("dataset_data_quality")
    )
  ),
  
  tabPanel(
    "Dataset Explorer",
    fluidPage(
      h2(class = "tab-page-title", "Dataset Explorer"),
      p(
        "Explore the variables available across the Rolls Collection. Browse variables within a specific study and dataset, ",
        "or search for a variable to see where it appears across studies."
      ),
      wellPanel(
        tags$strong("On this page"),
        tags$br(),
        tags$a(href = "#browse-dataset", "Browse a dataset"),
        tags$span("  |  "),
        tags$a(href = "#find-variable", "Find a variable across studies")
      ),
      tags$div(
        id = "browse-dataset",
        style = "scroll-margin-top: 20px;",
        h3(
          style = "font-weight: 700; margin-top: 28px;",
          "Browse a dataset"
        )
      ),
      p(
        "Select a study and dataset to view its variables and variable-level completeness."
      ),
      fluidRow(
        column(
          width = 5,
          selectInput(
            inputId = "directory_study",
            label = "Choose a study:",
            choices = dataset_explorer_study_choices,
            selected = dataset_explorer_study_choices[1]
          )
        ),
        column(
          width = 7,
          selectInput(
            inputId = "directory_dataset",
            label = "Choose a dataset:",
            choices = character(0)
          )
        )
      ),
      DTOutput("variables_for_dataset"),
      tags$hr(),
      tags$div(
        id = "find-variable",
        style = "scroll-margin-top: 20px;",
        h3(
          style = "font-weight: 700; margin-top: 28px;",
          "Find a variable across studies"
        )
      ),
      p(
        "Select a variable to see every study in the collection where that variable appears."
      ),
      selectizeInput(
        inputId = "directory_variable",
        label = "Choose a variable:",
        choices = dataset_explorer_variable_choices,
        selected = dataset_explorer_variable_choices[1],
        multiple = FALSE,
        options = list(placeholder = "Search for a variable")
      ),
      DTOutput("datasets_for_variable")
    )
  ),
  
  
  
  
)

server <- function(input, output, session) {
  
  observeEvent(input$study_quality_click, {
    req(input$study_quality_click$study)
    
    clicked_study <- input$study_quality_click$study
    
    normalize_study_name <- function(x) {
      x <- tolower(x)
      x <- gsub("^[0-9]{4}\\s+", "", x)
      x <- gsub("[^a-z0-9]", "", x)
      x
    }
    
    clicked_normalized <- normalize_study_name(clicked_study)
    choice_normalized <- vapply(
      data_quality_study_choices,
      normalize_study_name,
      character(1)
    )
    
    distances <- adist(clicked_normalized, choice_normalized)
    matched_study <- data_quality_study_choices[
      which.min(distances[1, ])
    ]
    
    cat(
      "Clicked:", clicked_study,
      "\nMatched Data Quality study:", matched_study,
      "\n\n"
    )
    
    updateSelectInput(
      session = session,
      inputId = "quality_study",
      choices = data_quality_study_choices,
      selected = matched_study
    )
    
    updateNavbarPage(
      session = session,
      inputId = "main_navigation",
      selected = "data_quality"
    )
  }, ignoreInit = TRUE)
  
  
  
  
  observeEvent(input$clear_overview_filters, {
    updateTextInput(session, "overview_search", value = "")
    updateCheckboxGroupInput(session, "overview_methods", selected = character(0))
    updateRadioButtons(session, "overview_nutrients", selected = "all")
    updateCheckboxGroupInput(session, "overview_demographics", selected = character(0))
    updateCheckboxGroupInput(session, "overview_questionnaires", selected = character(0))
  })
  
  overview_filtered <- reactive({
    dat <- overview
    
    search_text <- str_trim(if (is.null(input$overview_search)) "" else input$overview_search)
    if (nzchar(search_text)) {
      searchable_columns <- intersect(
        c("study", "dataset", "citation", "location", "year", "sample_age",
          "sample_sex", "description", "related_publications", "pub_doi"),
        names(dat)
      )
      search_matches <- Reduce(
        `|`,
        lapply(searchable_columns, function(column_name) {
          str_detect(
            coalesce(as.character(dat[[column_name]]), ""),
            regex(search_text, ignore_case = TRUE)
          )
        })
      )
      dat <- dat[search_matches, , drop = FALSE]
    }
    
    selected_characteristics <- c(
      input$overview_methods,
      input$overview_demographics,
      input$overview_questionnaires
    )
    selected_characteristics <- selected_characteristics[
      selected_characteristics %in% names(dat)
    ]
    
    # Retain rows marked 1 for every selected characteristic. Users can select
    # multiple items within a section or combine selections across sections.
    if (length(selected_characteristics) > 0) {
      characteristic_matches <- as.data.frame(
        lapply(dat[selected_characteristics], positive_flag),
        check.names = FALSE
      )
      keep <- rowSums(characteristic_matches, na.rm = TRUE) ==
        length(selected_characteristics)
      dat <- dat[keep, , drop = FALSE]
    }
    
    if (!is.null(input$overview_nutrients) &&
        input$overview_nutrients != "all" &&
        length(nutrient_columns) > 0) {
      nutrient_matches <- as.data.frame(
        lapply(dat[nutrient_columns], positive_flag),
        check.names = FALSE
      )
      any_nutrient_assessed <- rowSums(nutrient_matches, na.rm = TRUE) > 0
      
      if (input$overview_nutrients == "yes") {
        dat <- dat[any_nutrient_assessed, , drop = FALSE]
      } else if (input$overview_nutrients == "no") {
        dat <- dat[!any_nutrient_assessed, , drop = FALSE]
      }
    }
    
    dat
  })
  
  output$study_overview_table <- renderDT({
    table_data <- overview_filtered() %>%
      transmute(
        Study = paste0(
          '<a href="#" class="study-quality-link" data-study="',
          htmltools::htmlEscape(study_display, attribute = TRUE),
          '">',
          htmltools::htmlEscape(study_display),
          '</a>'
        ),
        Dataset = dataset_display,
        `Sample size` = sample_size,
        `Sample age` = sample_age,
        `Sample sex` = sample_sex,
        Location = location,
        Year = year,
        `Publication DOI` = mapply(
          format_doi_links,
          pub_doi,
          study,
          USE.NAMES = FALSE
        )
      )
    
    datatable(
      table_data,
      escape = FALSE,
      rownames = FALSE,
      filter = "top",
      options = list(
        pageLength = 15,
        scrollX = TRUE,
        autoWidth = TRUE
      )
    )
  })
  
  observeEvent(input$directory_study, {
    req(input$directory_study)
    
    dataset_choices <- variable_completeness %>%
      filter(study_display == input$directory_study) %>%
      distinct(Dataset) %>%
      arrange(Dataset) %>%
      pull(Dataset)
    
    dataset_choices_with_all <- c(
      "All datasets for this study",
      dataset_choices
    )
    
    updateSelectInput(
      session,
      "directory_dataset",
      choices = dataset_choices_with_all,
      selected = "All datasets for this study"
    )
  }, ignoreInit = FALSE)
  
  output$variables_for_dataset <- renderDT({
    req(input$directory_study, input$directory_dataset)
    
    result <- variable_completeness %>%
      filter(
        study_display == input$directory_study
      )
    
    if (input$directory_dataset != "All datasets for this study") {
      result <- result %>%
        filter(
          Dataset == input$directory_dataset
        )
    }
    
    result <- result %>%
      transmute(
        Dataset,
        Variable,
        Type,
        `Complete observations`,
        `Total observations`,
        `% complete`
      ) %>%
      arrange(Dataset, Variable)
    
    datatable(
      result,
      rownames = FALSE,
      filter = "top",
      options = list(pageLength = 15, scrollX = TRUE, autoWidth = TRUE)
    ) %>%
      formatRound(columns = "% complete", digits = 2)
  })
  
  output$datasets_for_variable <- renderDT({
    req(input$directory_variable)
    
    result <- variable_completeness %>%
      filter(Variable == input$directory_variable) %>%
      distinct(study_display) %>%
      transmute(Study = study_display) %>%
      arrange(Study)
    
    datatable(
      result,
      rownames = FALSE,
      filter = "none",
      class = "stripe hover",
      options = list(
        dom = "t",
        paging = FALSE,
        searching = FALSE,
        ordering = TRUE,
        autoWidth = TRUE,
        columnDefs = list(list(className = "dt-left", targets = "_all"))
      )
    )
  })
  
  quality_selected <- reactive({
    req(input$quality_study)
    
    data_quality %>%
      filter(
        study_display == input$quality_study
      )
  })
  
  dataset_quality_selected <- reactive({
    req(input$quality_study)
    
    dataset_data_quality %>%
      filter(
        study_display == input$quality_study
      )
  })
  
  output$data_quality <- renderDT({
    quality_table <- quality_selected() %>%
      arrange(`Data group`) %>%
      transmute(
        `Data group` = as.character(`Data group`),
        `# variables observed` = if_else(
          is.na(`# variables observed`), "NA", format(round(`# variables observed`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `Total data points` = if_else(
          is.na(`Total data points`), "NA", format(round(`Total data points`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `Total missing` = if_else(
          is.na(`Total missing`), "NA", format(round(`Total missing`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `% missing overall` = if_else(
          is.na(`% missing overall`),
          "NA",
          paste0(sprintf("%.2f", `% missing overall`), "%")
        ),
        `Mean % missing by participant` = if_else(
          is.na(`Mean % missing by participant`),
          "NA",
          paste0(sprintf("%.2f", `Mean % missing by participant`), "%")
        ),
        `Range of % missing by participant` = if_else(
          is.na(`Range of % missing by participant`) |
            !nzchar(str_trim(as.character(`Range of % missing by participant`))),
          "NA",
          as.character(`Range of % missing by participant`)
        ),
        `# complete cases` = if_else(
          is.na(`# complete cases`), "NA", format(round(`# complete cases`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `# participants ≥85% complete` = if_else(
          is.na(`# participants ≥85% complete`),
          "NA",
          format(round(`# participants ≥85% complete`), big.mark = ",", scientific = FALSE, trim = TRUE)
        )
      )
    
    datatable(
      quality_table,
      rownames = FALSE,
      options = list(
        dom = "t",
        paging = FALSE,
        searching = FALSE,
        ordering = FALSE,
        scrollX = TRUE,
        autoWidth = TRUE
      )
    )
  })
  
  output$dataset_data_quality <- renderDT({
    dataset_quality_table <- dataset_quality_selected() %>%
      arrange(Dataset) %>%
      transmute(
        Dataset,
        `# variables observed` = if_else(
          is.na(`# variables observed`), "NA", format(round(`# variables observed`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `Total data points` = if_else(
          is.na(`Total data points`), "NA", format(round(`Total data points`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `Total missing` = if_else(
          is.na(`Total missing`), "NA", format(round(`Total missing`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `% missing overall` = if_else(
          is.na(`% missing overall`),
          "NA",
          paste0(sprintf("%.2f", `% missing overall`), "%")
        ),
        `% data present` = if_else(
          is.na(`% data present`),
          "NA",
          paste0(sprintf("%.2f", `% data present`), "%")
        ),
        `Mean % missing by participant` = if_else(
          is.na(`Mean % missing by participant`),
          "NA",
          paste0(sprintf("%.2f", `Mean % missing by participant`), "%")
        ),
        `Range of % missing by participant` = if_else(
          is.na(`Range of % missing by participant`) |
            !nzchar(str_trim(as.character(`Range of % missing by participant`))),
          "NA",
          as.character(`Range of % missing by participant`)
        ),
        `# complete cases` = if_else(
          is.na(`# complete cases`), "NA", format(round(`# complete cases`), big.mark = ",", scientific = FALSE, trim = TRUE)
        ),
        `# participants ≥85% complete` = if_else(
          is.na(`# participants ≥85% complete`),
          "NA",
          format(round(`# participants ≥85% complete`), big.mark = ",", scientific = FALSE, trim = TRUE)
        )
      )
    
    datatable(
      dataset_quality_table,
      rownames = FALSE,
      filter = "top",
      options = list(
        pageLength = 15,
        scrollX = TRUE,
        autoWidth = TRUE
      )
    )
  })
  
  output$macro_status <- renderUI({
    status <- quality_selected() %>%
      pull(`Intake macros computed`) %>%
      na.omit() %>%
      unique()
    
    if (length(status) == 0) {
      status <- "NA"
    } else {
      status <- status[1]
    }
    
    tags$div(
      class = "card-like",
      style = "margin-top: 18px;",
      tags$strong("Intake macros computed: "),
      status
    )
  })
}

shinyApp(ui = ui, server = server)
